server:
  port: 8081
spring:
  application:
    name: lyylpaas
  redis:
    cluster:
      nodes:
      - 192.168.1.195:7000
  session:
    store-type: none
  rabbitmq:
    host: 192.168.1.198
    port: 5672
    username: admin
    password: admin
    virtualHost: /
mybatis:
    mapper-locations: classpath*:mybatis/mapper/**/*.xml
    #mapper-locations: classpath*:com/hhly/paas/mapper/*.xml
    type-aliases-package: com.hhly.paas.base.bean,com.hhly.basebusiness.bean
    configLocation: mybatis/mybatis-config.xml
#使用druid数据源
druid:
  url: jdbc:mysql://192.168.1.212:3306/videogame?characterEncoding=utf8
  driver-class: com.mysql.jdbc.Driver
  username: developer
  password: 123456
  max-active: 50 #最大连接池数量
  initial-size: 5 # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
  min-idle: 5 # 最小连接池数量
  test-on-borrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
  defaultAutoCommit: true #修改默认提交 true为自动提交
  timeBetweenEvictionRunsMillis: 60000 #有两个含义：#1) Destroy线程会检测连接的间隔时间 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 'x' #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，#testOnBorrow、testOnReturn、testWhileIdle都不会起作用
  testWhileIdle: true #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，#执行validationQuery检测连接是否有效。
  testOnReturn: false
  maxOpenPreparedStatements: 20 #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。#在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
  removeAbandoned: true  #打开 removeAbandoned 功能 与removeAbandonedTimeout配合使用
  removeAbandonedTimeout: 1800 #1800 秒，也就是 30 分钟
  logAbandoned: true #关闭 abanded 连接时输出错误日志
eureka:
  instance:
    prefer-ip-address: true
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://192.168.1.199:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

ftp:
    img:
      server: 192.168.1.223
      port: 21
      account: lyylftp
      password: 123456
      basepath:
    video:
      server: 192.168.1.223
      port: 21
      account: nginx
      password: nginx
      basepath:
    exportCvs:
      server: 192.168.74.159
      port: 21
      account: hyzb
      password: 654321
      basepath:
