server:
  port: 23101

spring:
  application:
    name: lawyer
    index: 0

  datasource:
    url: jdbc:mysql://localhost:3306/lawyer
    username: root
    password: 123456
    testWhileIdle: true
    validationQuery: SELECT 1
