server:
  port: 23411

spring:
#  application:
#    name: account
#    index: 0

  datasource:
    url: jdbc:mysql://localhost:3306/orderinfo
    username: root
    password: 123456
    testWhileIdle: true
    validationQuery: SELECT 1


feign:
  hystrix:
    enabled: true