# eureka.client.registerWithEureka ：表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false
# eureka.client.fetchRegistry ：表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
# eureka.client.serviceUrl.defaultZone ：设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
server:
  port: 1111

# 安全认证的配置
security:
  basic:
    enabled: true
  user:
    name: chssfaa  # 用户名
    password: chaiswwww123456   # 用户密码

# Configure this Discovery Server
eureka:
  instance:
    # hostname: localhost
    preferIpAddress: true
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@10.37.61.36:${server.port}/eureka/
#      eureka.client.serviceUrl.defaultZone=http://peer2:1112/eureka/
#
  server:
    enable-self-preservation: false

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf


# 默认会去找 classpath 下的 logback.xml. 为了达到 profile 的目的故意不用这个文件名
logging.config: classpath:log-prod.xml