server:
  port: 8986

spring:
  application:
    name: configs

#  profiles:
#     active: native

  cloud:
    config:
       server:
         # git管理配置
         git:
           uri: http://192.168.10.81/java/commline/config-git.git
#           searchPaths: config-repo
           username: configuser
           password: configuser

#          uri: file:///E:/develop/platform/config-repo
#          basedir: target/config
#          searchPaths: "*"
#           native:
#            searchLocations: file:///E:/develop/lawyerplatform/lawyerplatform/config-repo
#    stream:
#        instanceCount: 1
#        instanceIndex: 0
#        kafka:
#          binder:
#            brokers: 192.168.10.224:9092, 192.168.10.224:9093, 192.168.10.224:9094
#            zkNodes: 192.168.10.224:2181
#            offsetUpdateTimeWindow: 10000
#            #offsetUpdateCount: 0
#            requiredAcks: 1
#            minPartitionCount: 1
#            replicationFactor: 1
#
#          bindings:
#            input:
#              consumer:
#                autoCommitOffset: true
#                startOffset: earliest
#                headerMode: raw
#            output:
#              producer:
#                bufferSize: 16384
#                sync: true
#                batchTimeout: 0

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

  client:
    serviceUrl:
      defaultZone: http://192.168.10.224:1122/eureka/
